### ISSUE TITLE
The gear editor injects properly, but no items appear upon mission start/restart

### ISSUE THREAD

**Issue by Dissentrix** [dom-ve/hitman2ge#1]
Hi, I downloaded the latest archive [here](https://github.com/dom-ve/hitman2ge/releases/tag/v1.1), and the menu opens properly when I run the injector, with the item list ; however, whether it's before starting a mission, or after (and then restarting), I can't seem to get the items to spawn in my inventory.

**Comment by gameplayoffert** [comment]
yes me too i can't get item in my inventory. I enable it and i select item and i restart but i have nothing.

**Comment by dom-ve** [comment]
still appears to be working for me on the last update, make sure your game is up to date and the mod is enabled

may i ask what windows version you're running?

**Comment by gameplayoffert** [comment]
hi, i have download my game on steam so i think he is up to date i and can see "2.72" on the launcher. I use the mod in sapienza same of you and i open the main menu after i open you cheat menu and i select the weapon and i enable it and i restart and it doesn't work. I'm not in exclusive fullscreen but normal full screen and i have direct x 11

**Comment by gameplayoffert** [comment]
but the injector and .dll is not in the hitman2 folder so that is a problem ?

**Comment by Dissentrix** [comment]
Same as gameplayoffert above - I haven't checked the gameplay version, but it should be the latest since I have the Steam game. I'm on Windows 10, which I assume should work, and I did click enable on the mod.

I assumed we could launch the injector from wherever, but maybe I should do it from my C: drive (the game is installed on an external HDD, and I launch the injector from there as well). Come to think of it, it might be worth reinstalling on the base drive, because I know Windows is iffy when it comes to external disks and administrator rights. I'll do that and report back.

Otherwise, my only ideas would be place the injector/dll somewhere in the hitman folder, as suggested above, or maybe some sort of issue with the Hitman 1 Legacy maps (I tried it in Paris, not in any H2 maps).

**Comment by gameplayoffert** [comment]
Same as Dissentrix my Hitman2 is installed on an internal hdd but the "D:\" not "C:\" but i don't know if that is the problem. And i have test it on "H2 map" Miami but it doesn't work too.

**Comment by gameplayoffert** [comment]
i have tried to recompile your cheat but i can't i have a lot of error

**Comment by gameplayoffert** [comment]
My computer : Windows 8.1 | Injected When In The Main Menu | Injector Is In The Retail Folder Of Hitman 2 Location | A Video Made By Me : https://www.youtube.com/watch?v=SkqpG66-t5w | And I'm In online mod | I have do the same thing in offline mod and it doesn't work too.

**Comment by gameplayoffert** [comment]
Dissentrix it work but only if you have the randomizer mod. i have installed randomizer mod and when i select an item and i restart my game it work. So test but i think it's that

**Comment by Dissentrix** [comment]
Oh really? But can you bypass the randomizer mod? I don't really want to have an unpredictable experience for guards.

**Comment by gameplayoffert** [comment]
yes i think i will try it

**Comment by gameplayoffert** [comment]
edit : yes you can you need to change all "DEFAULT" to "NONE" in the "ZHM5Randomizer.ini" file and after the Randomizer mod is disabled but the "Gear Editor" always work so you can and if i doesn't work remove all "GUID" in the "DefaultItemPools.json" and "IgnoreList.json"

**Comment by Dissentrix** [comment]
Oh that's perfect, I'll try that tomorrow and report back - thanks!

**Comment by gameplayoffert** [comment]
ok

**Comment by Dissentrix** [comment]
All right it works, perfect. To the author of the mod: I would recommend specifying that you do need the Item Randomizer mod to make this work, apparently.

**Comment by gameplayoffert** [comment]
ok perfect

**Comment by dom-ve** [comment]
it does not _need_ the item randomizer mod, but instead uses it's functions as a fallback if it is installed

i'm glad you got it working, from what i've gathered it might somehow be related to the game language but i haven't looked at it too much since i rarely play hitman 2 nowadays

**Comment by gameplayoffert** [comment]
ok and i have an other question ? for the address\offset for weapons you have get it with cheat engine ? or cheat engine and an other software ?
